# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
