# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyInici', models.IntegerField()),
                ('anyFi', models.IntegerField()),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anyacademic_centre', to='quickstart.Centre')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitat',
            name='assignatura',
        ),
        migrations.RemoveField(
            model_name='assignatura',
            name='centre',
        ),
        migrations.AddField(
            model_name='trimestre',
            name='assignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trimestre_assignatura', to='quickstart.Assignatura'),
        ),
        migrations.AddField(
            model_name='activitat',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitat_trimestre', to='quickstart.Trimestre'),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='anyAcademic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignatura_anyacademic', to='quickstart.AnyAcademic'),
        ),
    ]
