# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180212_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('ponderacio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('congnom_1', models.CharField(blank=True, max_length=100)),
                ('congnom_2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacio', models.IntegerField(default=0)),
                ('activitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Activitat')),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Alumne')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignatura',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curs',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='congnom_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='congnom_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumne',
            name='activitats',
            field=models.ManyToManyField(related_name='treballa', through='quickstart.Qualificacio', to='quickstart.Activitat'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='assignatures',
            field=models.ManyToManyField(related_name='cursa', to='quickstart.Assignatura'),
        ),
        migrations.AddField(
            model_name='professor',
            name='centres',
            field=models.ManyToManyField(related_name='centres_assignats', to='quickstart.Centre'),
        ),
    ]
