# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180312_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('curs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup_curs', to='quickstart.Curs')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumne',
            name='curs',
        ),
        migrations.AddField(
            model_name='alumne',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_grup', to='quickstart.Grup'),
        ),
    ]
