# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20180326_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='grup',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup_centre', to='quickstart.Centre'),
        ),
    ]
