# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20180216_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='nivell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivell', to='quickstart.Nivell'),
        ),
    ]
