# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20180412_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacio',
            name='qualificacio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
