# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_activitat_avaluable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='centres',
        ),
        migrations.AddField(
            model_name='alumne',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_centre', to='quickstart.Centre'),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignatura_centre', to='quickstart.Centre'),
        ),
        migrations.AlterField(
            model_name='assignatura',
            name='curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignatura_curs', to='quickstart.Curs'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='nivell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curs_nivell', to='quickstart.Nivell'),
        ),
    ]
