# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20180216_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='nivell',
            field=models.CharField(choices=[('eso', 'ESO'), ('batxillerat', 'Batxillerat')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Nivell',
        ),
    ]
