# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20180501_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_naixement',
            field=models.DateField(blank=True),
        ),
    ]
