# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20180218_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumne',
            name='activitats',
        ),
        migrations.RemoveField(
            model_name='alumne',
            name='assignatures',
        ),
        migrations.AddField(
            model_name='activitat',
            name='alumnes',
            field=models.ManyToManyField(related_name='treballada', to='quickstart.Alumne'),
        ),
        migrations.AddField(
            model_name='activitat',
            name='assignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitat_assignatura', to='quickstart.Assignatura'),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='alumnes',
            field=models.ManyToManyField(related_name='cursada', to='quickstart.Alumne'),
        ),
    ]
