# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20180220_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignatura',
            name='alumnes',
        ),
        migrations.AddField(
            model_name='alumne',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_curs', to='quickstart.Curs'),
        ),
    ]
